<a href="https://colab.research.google.com/github/chromanista/Color-Chart-Extractor/blob/main/Chart_Extract.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Imports
import numpy as np
import PIL
#print('PIL',PIL.__version__)

In [ ]:
'''chart_details = {
    "name": "ColorChecker Video",
    "cells": [
        {"x_pos": 0, "y_pos": 0},
        {"x_pos": 0, "y_pos": 20},
        {"x_pos": 0, "y_pos": 40},
        {"x_pos": 0, "y_pos": 60},
        {"x_pos": 0, "y_pos": 80},
        {"x_pos": 0, "y_pos": 100},
        {"x_pos": 0, "y_pos": 120},
        {"x_pos": 20, "y_pos": 0},
        {"x_pos": 20, "y_pos": 20},
        {"x_pos": 20, "y_pos": 40},
        {"x_pos": 20, "y_pos": 60},
        {"x_pos": 20, "y_pos": 80},
        {"x_pos": 20, "y_pos": 100},
        {"x_pos": 20, "y_pos": 120},
        {"x_pos": 100, "y_pos": 0},
        {"x_pos": 100, "y_pos": 20},
        {"x_pos": 100, "y_pos": 40},
        {"x_pos": 100, "y_pos": 60},
        {"x_pos": 100, "y_pos": 80},
        {"x_pos": 100, "y_pos": 100},
        {"x_pos": 100, "y_pos": 120},
        {"x_pos": 120, "y_pos": 0},
        {"x_pos": 120, "y_pos": 20},
        {"x_pos": 120, "y_pos": 40},
        {"x_pos": 120, "y_pos": 60},
        {"x_pos": 120, "y_pos": 80},
        {"x_pos": 120, "y_pos": 100},
        {"x_pos": 120, "y_pos": 120}

  ]
}'''

chart_details = {
    "name": "ColorChecker Classic",
    "cells": [
        {"x_pos": 50, "y_pos": 70},
        {"x_pos": 295, "y_pos": 70},
        {"x_pos": 540, "y_pos": 70},
        {"x_pos": 785, "y_pos": 70},
        {"x_pos": 1035, "y_pos": 70},
        {"x_pos": 1280, "y_pos": 70},
        {"x_pos": 50, "y_pos": 315},
        {"x_pos": 295, "y_pos": 315},
        {"x_pos": 540, "y_pos": 315},
        {"x_pos": 785, "y_pos": 315},
        {"x_pos": 1035, "y_pos": 315},
        {"x_pos": 1280, "y_pos": 315},
        {"x_pos": 50, "y_pos": 70},
        {"x_pos": 295, "y_pos": 560},
        {"x_pos": 540, "y_pos": 560},
        {"x_pos": 785, "y_pos": 560},
        {"x_pos": 1035, "y_pos": 560},
        {"x_pos": 1280, "y_pos": 560},
        {"x_pos": 50, "y_pos": 800},
        {"x_pos": 295, "y_pos": 800},
        {"x_pos": 540, "y_pos": 800},
        {"x_pos": 785, "y_pos": 800},
        {"x_pos": 1035, "y_pos": 800},
        {"x_pos": 1280, "y_pos": 800}
  ]
}
SIZE = 175

In [ ]:
print(chart_details)

{'name': 'ColorChecker Video', 'cells': [{'x_pos': 0, 'y_pos': 0}, {'x_pos': 0, 'y_pos': 20}, {'x_pos': 0, 'y_pos': 40}, {'x_pos': 0, 'y_pos': 60}, {'x_pos': 0, 'y_pos': 80}, {'x_pos': 0, 'y_pos': 100}, {'x_pos': 0, 'y_pos': 120}, {'x_pos': 20, 'y_pos': 0}, {'x_pos': 20, 'y_pos': 20}, {'x_pos': 20, 'y_pos': 40}, {'x_pos': 20, 'y_pos': 60}, {'x_pos': 20, 'y_pos': 80}, {'x_pos': 20, 'y_pos': 100}, {'x_pos': 20, 'y_pos': 120}, {'x_pos': 100, 'y_pos': 0}, {'x_pos': 100, 'y_pos': 20}, {'x_pos': 100, 'y_pos': 40}, {'x_pos': 100, 'y_pos': 60}, {'x_pos': 100, 'y_pos': 80}, {'x_pos': 100, 'y_pos': 100}, {'x_pos': 100, 'y_pos': 120}, {'x_pos': 120, 'y_pos': 0}, {'x_pos': 120, 'y_pos': 20}, {'x_pos': 120, 'y_pos': 40}, {'x_pos': 120, 'y_pos': 60}, {'x_pos': 120, 'y_pos': 80}, {'x_pos': 120, 'y_pos': 100}, {'x_pos': 120, 'y_pos': 120}]}


In [ ]:
# @title Form Title
opt = "Option 1" # @param ["Option 1","Option 2","Option 3"]
from google.colab import files
from IPython.display import Image

uploaded = files.upload()

filename = ''
for img in uploaded.keys():
  filename = img
  #break
Image(filename)

Saving colorchecker-classic_01.png to colorchecker-classic_01.png


In [ ]:
filename = ''
for img in uploaded.keys():
  filename = img
  #break

img = PIL.Image.open(filename)


In [ ]:
numpydata = np.asarray(img)

# <class 'numpy.ndarray'>
print(type(numpydata))

#  shape
print(numpydata.shape)
#SIZE = 3
samples_list = []
for chip in chart_details["cells"]:
  sample_data = numpydata[ chip["y_pos"]:chip["y_pos"] + SIZE, chip["x_pos"]:chip["x_pos"] + SIZE ]
  samples_list.append(sample_data.mean(axis=(0,1)))
  #print(sample_data.mean(axis=(0,1)))
  #break

samples_array = np.array(samples_list)[0:, :3]
print(samples_array.shape)
print(samples_array)
np.savetxt('data.csv', samples_array, delimiter=',', fmt='%8f')

<class 'numpy.ndarray'>
(1080, 1543, 4)
(24, 3)
[[179.20398367 100.48202449  69.87627755]
 [245.99516735 209.67030204 203.37263673]
 [151.00607347 181.37394286 219.89404082]
 [103.20747755 143.18517551  10.98788571]
 [198.26429388 197.24097959 232.13126531]
 [188.8011102  238.96310204 232.60267755]
 [254.52166531 142.91647347  14.26164898]
 [113.82654694 132.02367347 228.13982041]
 [254.46922449 120.84280816 140.64891429]
 [102.7530449   10.58174694 121.55947755]
 [194.20401633 240.1648      68.65541224]
 [254.45485714 189.92803265   1.18693878]
 [179.20398367 100.48202449  69.87627755]
 [ 15.14817959 220.32235102 101.82040816]
 [250.18713469   5.55301224  26.89779592]
 [254.81146122 228.85090612   0.98044082]
 [254.96124082 139.56979592 210.37893878]
 [ 42.86269388 193.86674286 235.02037551]
 [249.1968     249.1968     249.1968    ]
 [240.59702857 240.59941224 240.59885714]
 [223.51487347 223.49942857 223.51428571]
 [183.16466939 179.17910204 180.22716735]
 [ 95.67758367  93.29244082 